###############################################################################
# Playbook for setting up a new Arch Linux system
#
# Preparation of the target system is required before running this, see the
# README.md file
###############################################################################

---
- hosts: all
  gather_facts: True
  roles: 
    - role: initial-steps
      tags: initial-steps
    - role: disk-prep
      tags: disk-prep
    - role: installation
      tags: installation
    - role: configuration
      tags: configuration
    - role: capsctrl
      tags: capsctrl
