# Setup is required before running this, see the README.md file

---
- hosts: new-system
  gather_facts: True
  roles: 
    - verify-efi
    - update-clock
    - role: disk-prep
      tags: disk-prep
    - role: installation
      tags: installation
    - role: configuration
      tags: configuration
