###############################################################################
# Configure Arch Linux
###############################################################################
---

- name: Set the time zone
  command: arch-chroot /mnt ln -sf "/usr/share/zoneinfo/{{ zone }}" /etc/localtime
  tags: zone

- name: Configure the hardware clock
  command: arch-chroot /mnt hwclock --systohc
  tags: clock

- name: Setup locale
  block:
  - name: Set the locale in locale.gen
    replace:
      path: /mnt/etc/locale.gen
      regexp: "^#(en_US.UTF-8.*)"
      replace: '\1'

  - name: Generate the locale
    command: arch-chroot /mnt locale-gen

  - name: Create the locale conf file
    copy:
      dest: /mnt/etc/locale.conf
      content: "LANG=en_US.UTF-8\n"
      force: no
    tags: localeconf
  tags: locale

- name: Set up hostname
  block:
    - name: Create the hostname file
      copy:
        dest: /mnt/etc/hostname
        content: "{{ hostname }}\n"
        force: no

    - name: Add this host the hosts file
      blockinfile:
        path: /mnt/etc/hosts
        block: |
          127.0.0.1  localhost
          ::1        localhost
          127.0.1.1  {{ hostname }}.localdomain  {{ hostname }}
  tags: hostname

- name: Configure initramfs
  block:
  - name: Modify the mkinitcpio.conf HOOKS to add encrypt
    replace:
      path: /mnt/etc/mkinitcpio.conf
      regexp: '^(HOOKS.*block)( filesystems.*)$'
      replace: '\1 encrypt\2'

  - name: Generate the initramfs
    command: arch-chroot /mnt mkinitcpio -p linux
    tags: mkinitcpio
  tags: initramfs

- name: Configure the boot loader
  block:
  - name: Install systemd-boot
    command: arch-chroot /mnt bootctl --path=/boot install
    tags: bootctl

  - name: Discover the root partition's UUID
    command: blkid --match-tag=UUID --output=value {{ root_part }}
    register: root_uuid

  - name: Create the bootloader loader config
    copy:
      src: loader.conf
      dest: /mnt/boot/loader/loader.conf

  - name: Configure the arch bootloader entry
    template:
      src: arch.conf.j2
      dest: /mnt/boot/loader/entries/arch.conf
  tags: bootloader

- name: Enable paccache clean-up timer
  command: arch-chroot /mnt systemctl enable paccache.timer
  tags: paccache

- name: Enable the ssh daemon
  command: arch-chroot /mnt systemctl enable sshd
  tags: ssh

- name: Enable sudo for users in the `wheel` group
  lineinfile:
    path: /mnt/etc/sudoers
    regexp: "^# %wheel ALL=\\(ALL:ALL\\) ALL"
    line: "%wheel ALL=(ALL:ALL) ALL"
    validate: 'visudo -cf %s'
  tags: sudoers

- name: Create the initial user account
  block:
  - name: Create the initial user account
    command: arch-chroot /mnt useradd -m -g users -G wheel,games,network,audio,optical,scanner -s /bin/bash "{{ first_user }}"
  - name: Set the initial user account password
    command: arch-chroot /mnt usermod --password "{{ first_pw | password_hash('sha512') }}" "{{ first_user }}"
  tags: add_user
