###############################################################################
# Configure Arch Linux
###############################################################################
---

- name: Set the time zone
  shell: arch-chroot /mnt ln -sf "/usr/share/zoneinfo/{{ zone }}" /etc/localtime
  tags: zone

- name: Configure the hardware clock
  shell: arch-chroot /mnt hwclock --systohc
  tags: clock

- name: Setup locale
  block:
  - name: Set the locale in locale.gen
    replace:
      path: /mnt/etc/locale.gen
      regexp: "^#(en_US.UTF-8.*)"
      replace: '\1'

  - name: Generate the locale
    shell: arch-chroot /mnt locale-gen

  - name: Create the locale conf file
    copy:
      dest: /mnt/etc/locale.conf
      content: "LANG=en_US.UTF-8\n"
      force: no
    tags: localeconf
  tags: locale

- name: Set up hostname
  block:
    - name: Create the hostname file
      copy:
        dest: /mnt/etc/hostname
        content: "{{ hostname }}\n"
        force: no

    - name: Add this host the hosts file
      blockinfile:
        path: /mnt/etc/hosts
        block: |
          127.0.0.1  localhost
          ::1        localhost
          127.0.1.1  {{ hostname }}.localdomain  {{ hostname }}
  tags: hostname

- name: Configure initramfs
  block:
  - name: Modify the mkinitcpio.conf HOOKS to add encrypt
    replace:
      path: /mnt/etc/mkinitcpio.conf
      regexp: '^(HOOKS.*block)( filesystems.*)$'
      replace: '\1 encrypt\2'

  - name: Generate the initramfs
    shell: arch-chroot /mnt mkinitcpio -p linux
    tags: mkinitcpio
  tags: initramfs
