###############################################################################
# Update the system clock
###############################################################################
---

- name: Update the system clock
  shell: timedatectl set-ntp true
