###############################################################################
# Verify this system has uefi capability
###############################################################################
---

- name: Update the system clock
  shell: timedatectl set-ntp true
