###############################################################################
# Install Arch Linux on the drive
###############################################################################
---

- name: Set the pacman mirror
  lineinfile:
    path: /etc/pacman.d/mirrorlist
    state: present
    insertafter: "^$"
    firstmatch: yes
    line: "{{ mirror }}\n"
  tags: mirror

- name: Install essential packages
  command:
    argv:
      - pacstrap
      - -K
      - /mnt
      - base
      - base-devel
      - linux
      - linux-firmware
      - man-db
      - openssh
      - pacman-contrib  # pacdiff, paccache
      - vim
      # I like netctl for networking
      - netctl  # Nice wired/wireless manager with profiles
      - wpa_supplicant  # For wireless networking
      - dialog  # For wifi-menu
      - dhcpcd  # For DHCP, of course
  args:
    creates: /mnt/bin
  tags: pacstrap

- name: Generate the fstab file
  shell: genfstab -U /mnt >> /mnt/etc/fstab
  tags: genfstab

- name: Add the swap space to the fstab
  lineinfile:
    path: /mnt/etc/fstab
    line: "{{ swap_path }}  none  swap  defaults  0  0"
  tags: swap
