###############################################################################
# Install Arch Linux on the drive
###############################################################################
---

- name: Set the pacman mirror
  lineinfile:
    path: /etc/pacman.d/mirrorlist
    state: present
    insertafter: "^$"
    firstmatch: yes
    line: "{{ mirror }}\n"
  tags: mirror

- name: Install the Arch base packages
  command:
    argv:
      - pacstrap
      - /mnt
      - base
      - base-devel
      - dialog  # Needed for wifi-menu
      - vim
      - wpa_supplicant  # Needed for wireless networking
  args:
    creates: /mnt/bin
  tags: pacstrap

- name: Generate the fstab file
  shell: genfstab -U /mnt >> /mnt/etc/fstab
  tags: genfstab
