###############################################################################
# Install Arch Linux on the drive
###############################################################################
---

- name: Set the pacman mirror
  lineinfile:
    path: /etc/pacman.d/mirrorlist
    state: present
    insertafter: "^$"
    firstmatch: yes
    line: "{{ mirror }}\n"
  tags: mirror

- name: Install essential packages
  command:
    argv:
      - pacstrap
      - /mnt
      - base
      - linux
      - linux-firmware
      - base-devel
      - vim
      # If you'll be doing the whole shebang
      #- netctl  # Nice wired/wireless manager with profiles
      #- wpa_supplicant  # For wireless networking
      #- dhcpcd  # For DHCP, of course
      #- dialog  # For wifi-menu
  args:
    creates: /mnt/bin
  tags: pacstrap

- name: Generate the fstab file
  shell: genfstab -U /mnt >> /mnt/etc/fstab
  tags: genfstab
