###############################################################################
# Install Arch Linux on the drive
###############################################################################
---

- name: Set the pacman mirror
  lineinfile:
    path: /etc/pacman.d/mirrorlist
    state: present
    insertafter: "^$"
    firstmatch: yes
    line: "{{ mirror }}\n"
  tags: mirror

- name: Install essential packages
  command:
    argv:
      - pacstrap
      - -K
      - /mnt
      - base
      - base-devel
      - linux
      - linux-firmware
      - man-db
      - openssh
      - pacman-contrib  # pacdiff, paccache
      - vim
      - networkmanager
  args:
    creates: /mnt/bin
  tags: pacstrap

- name: Generate the fstab file
  shell: genfstab -U /mnt >> /mnt/etc/fstab
  tags: genfstab
