###############################################################################
# Verify this system has uefi capability
###############################################################################
---

- name: Verify the boot mode
  stat:
    path: /sys/firmware/efi/efivars
  register: efivars

- fail:
    msg: Target system is not UEFI-capabile. Aborting.
  when: efivars.stat.exists == false
