###############################################################################
# Prepare the hard drive partitions
###############################################################################
---

- name: Partition the first hard drive
  command: "sgdisk {{ item }} {{ drive0 }}"
  with_items:
    - --zap-all
    - --new=1:0:+{{ boot_part_size }} --typecode=1:EF00 --change-name=1:boot
    - --largest-new=2 --typecode=2:8309 --change-name=2:root0
  tags: partition

- name: Partition the second hard drive
  command: "sgdisk {{ item }} {{ drive1 }}"
  with_items:
    - --zap-all
    - --largest-new=1 --typecode=1:8309 --change-name=1:root1
  when: drive1 is defined
  tags: partition

- name: LVM2 pv and vg tasks
  block:
  - name: Create the LVM2 physical volume
    command: "pvcreate {{ item }}"
    with_items:
      - "{{ root_pv0 }}"
  - name: Create the LVM2 volume group
    command: "vgcreate {{ volume_group }} {{ root_pv0 }}"
  when: drive1 is not defined

- name: LVM2 pv and vg tasks
  block:
  - name: Create the LVM2 physical volumes
    command: "pvcreate {{ item }}"
    with_items:
      - "{{ root_pv0 }}"
      - "{{ root_pv1 }}"
  - name: Create the LVM2 volume group
    command: "vgcreate {{ volume_group }} {{ root_pv0 }} {{ root_pv1 }}"
  when: drive1 is defined

- name: Create the LVM2 logical volume
  command: "lvcreate -l 100%FREE -n {{ root_lv }} {{ volume_group }}"
