# Set these variables for your new system

# The new machine name
hostname: mycoolmachine

# Hard drive device and partition info
# With PCIe SSDs these may be /dev/nvme0n1, /dev/nvme0n1p1 and /dev/nvme0n1p2
drive: /dev/sdX  # Set this to the drive we want to install Arch on
boot_part: /dev/sdX1  # Adjust this accordingly
root_part: /dev/sdX2  # This too

# Change to something secure!
luks_pass: "foo bar baz"

# Probably will never change this
cryptroot: /dev/mapper/cryptroot

# Swap file
swap_path: /swapfile
# This value is in megabytes and will result in a 32G swap file
# For a much smaller one (say for testing), try 512 which will make a 0.5G swap file
swap_size: 32768

# Use a mirror you know is close and fast
mirror: "Server = http://mirror.umd.edu/archlinux/$repo/os/$arch"

# Relative to /usr/share/zoneinfo/
zone: America/New_York

# Change these as needed and change this password immediately on the new
# system!
first_user: archie
first_pw: archie1
