# Set these variables for your new system

# The new machine name
hostname: mycoolmachine

# Hard drive device and partition info
drive: /dev/sda  # Set this to the drive we want to install Arch on
boot_part: /dev/sda1  # Adjust this accordingly
root_part: /dev/sda2  # This too

# Change to something secure!
luks_pass: "foo bar baz"

# Probably will never change this
cryptroot: /dev/mapper/cryptroot

# Use a mirror you know is close and fast
mirror: "Server = http://mirror.umd.edu/archlinux/$repo/os/$arch"

# Relative to /usr/share/zoneinfo/
zone: America/New_York
