# Set these variables for your new system

# The new machine name
hostname: mycoolmachine

# Hard drive device and partition info
# With PCIe SSDs these may be /dev/nvme0n1, /dev/nvme0n1p1 and /dev/nvme0n1p2
# In this configuration, we're combining two PVs in the volume group into one
# LV for the root partition.
drive0: /dev/nvme0n1
drive1: /dev/nvme1n1
boot_part: /dev/nvme0n1p1
root_part0: /dev/nvme0n1p2
root_part1: /dev/nvme1n1p1

# Change to something secure!
luks_pass: "foo bar baz"

# Probably won't need to change these
volume_group: vg1
# The logical volume for our entire / partition which is encrypted
lvroot: /dev/vg1/cryptroot
# After cryptsetup open, this is what we mount as /
cryptroot: /dev/mapper/root

# Use a mirror you know is close and fast
mirror: "Server = http://mirror.umd.edu/archlinux/$repo/os/$arch"

# Relative to /usr/share/zoneinfo/
zone: America/New_York

# Change these as needed and change this password immediately on the new
# system!
first_user: archie
first_pw: archie1
