# Set these variables for your new system

# The new machine name
hostname: mycoolmachine

# Hard drive device and partition info
# With PCIe SSDs these may be /dev/nvme0n1, /dev/nvme0n1p1 and /dev/nvme0n1p2
# In this configuration, we're combining two PVs in the volume group into one
# LV for the root partition.
drive0: /dev/nvme0n1
boot_part: /dev/nvme0n1p1
root_part0: /dev/nvme0n1p2

# If you are combining two drives into one big storage with LVM2, uncomment
# these and set them correctly
# drive1: /dev/nvme1n1
# root_part1: /dev/nvme1n1p1

# This used to be "512M" but these days it's common to use "1G"
boot_part_size: "1G"

# Change to something secure!
# Comment luks_pass out to disable full drive encryption altogether
luks_pass: "foo bar baz"

# Probably won't need to change these
volume_group: vg1
# The logical volume for our entire / partition which is encrypted
root_lv: cryptroot
# lvroot: /dev/vg1/cryptroot
# After cryptsetup open, this is what we mount as /
cryptroot: /dev/mapper/root

# Swap file
swap_path: /swapfile
# This value is in megabytes and will result in a 32G swap file
# For a much smaller one (say for testing), try 512 which will make a 0.5G swap file
swap_size: 32768

# Use a mirror you know is close and fast
mirror: "Server = http://mirror.umd.edu/archlinux/$repo/os/$arch"

# Relative to /usr/share/zoneinfo/
zone: America/New_York

# Change these as needed and change this password immediately on the new
# system!
first_user: archie
first_pw: archie1
